### ISSUE TITLE
Add support for Cirrus CI

### ISSUE THREAD

**Issue by trivikr** [codecov/codecov-bash#217] opened 2019-10-25 19:47 UTC
Refs: https://github.com/codecov/codecov-node/issues/139#issuecomment-546433239

This should be similar to https://github.com/codecov/codecov-bash/pull/199

**Comment by fkorotkov** [comment] 2019-10-25 22:01
Duplicate of #127

**Comment by fkorotkov** [comment] 2019-10-25 22:02
Duplicate of #127

**Comment by drazisil** [comment] 2019-11-18 14:41
Closing in favor of #127

**Closed by drazisil** 2019-11-18 14:41 UTC
