### ISSUE TITLE
bash-codecov takes about a minute with many files

### ISSUE THREAD

**Issue by wilzbach** [codecov/codecov-bash#38] opened 2016-08-12 05:03 UTC
Just as an FYI with many files (atm 162) codecov-bash takes a quite noticable time to read all reports. In fact compiling all those files is about as fast as codecov ;-)

See e.g. this build:

https://circleci.com/gh/dlang/phobos/13

(when watched "live" it felt like it spent all the time on "reading the reports")

**Comment by stevepeak** [comment] 2016-08-12 16:33
I'm seeing 44s on the Codecov job. Do you have a suggestion on how to speed up reading files? https://github.com/codecov/codecov-bash/blob/master/codecov#L886-L917

**Comment by nijel** [comment] 2016-08-25 15:03
I've just faced same issue.

The problem is not reading but concatenating them in memory - this is quite slow in bash. What might be better approach is to prepare request data in temporary file (it's anyway just concatenating them).

https://github.com/codecov/codecov-bash/blob/master/codecov#L912-L915

PS: I've currently workarounded by uloading files in chunks as it's way faster than doing many of them at once.

**Comment by stevepeak** [comment] 2016-08-25 15:11
@nijel I would love to implement this. Can you help me understand on what technique you are suggesting?

**Comment by nijel** [comment] 2016-08-25 15:20
See https://github.com/codecov/codecov-bash/pull/39 (completely untested)

**Comment by stevepeak** [comment] 2016-08-27 11:31
Resolving soon thanks to @nijel contributions 👍

**Closed by stevepeak** 2016-08-27 11:31 UTC
