### ISSUE TITLE
AppVeyor not detected anymore (regression)

### ISSUE THREAD

**Issue by blueyed** [codecov/codecov-bash#271] opened 2020-02-26 21:38 UTC
It seems like the script does not detect AppVeyor correctly anymore?
(AFAIK this used to work, but now failed on CI)

```
  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-20200214-585fef0
x> No CI provider detected.
    Testing inside Docker? http://docs.codecov.io/docs/testing-with-docker
    Testing with Tox? https://docs.codecov.io/docs/python#section-testing-with-tox
    project root: C:/projects/pdbpp
    Yaml found at: codecov.yml
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    + coverage-travis.xml bytes=85251
==> Gzipping contents
==> Uploading reports
    url: https://codecov.io
    query: branch=&commit=989e62c46a63952e2b60024b615325465d93f73b&build=&build_url=&name=py27&tag=&slug=pdbpp%2Fpdbpp&service=&flags=windows,py27&pr=&job=
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-20200214-585fef0&token=secret&branch=&commit=989e62c46a63952e2b60024b615325465d93f73b&build=&build_url=&name=py27&tag=&slug=pdbpp%2Fpdbpp&service=&flags=windows,py27&pr=&job=
HTTP 400
Please provide the repository token to upload reports via `-t :repository-token`
```

It worked 10 days ago:
```
  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-20191211-b8db533
==> Appveyor CI detected.
    project root: C:/projects/pdbpp
    Yaml found at: codecov.yml
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    + coverage-travis.xml bytes=85251
==> Gzipping contents
==> Uploading reports
    url: https://codecov.io
    query: branch=master&commit=6a07527dbf96d8d0534fc16ff90d77ad88ba9db3&build=gkymf1pxlxuturf7&build_url=https%3A%2F%2Fci.appveyor.com%2Fproject%2Fpdbpp%2Fpdbpp%2Fbuilds%2F30841038%2Fjob%2Fgkymf1pxlxuturf7&name=py27&tag=&slug=pdbpp%2Fpdbpp&service=appveyor&flags=windows,py27&pr=&job=blueyed%2Fpdbpp%2F1.0.59
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-20191211-b8db533&token=secret&branch=master&commit=6a07527dbf96d8d0534fc16ff90d77ad88ba9db3&build=gkymf1pxlxuturf7&build_url=https%3A%2F%2Fci.appveyor.com%2Fproject%2Fpdbpp%2Fpdbpp%2Fbuilds%2F30841038%2Fjob%2Fgkymf1pxlxuturf7&name=py27&tag=&slug=pdbpp%2Fpdbpp&service=appveyor&flags=windows,py27&pr=&job=blueyed%2Fpdbpp%2F1.0.59
    -> Uploading
    -> View reports at https://codecov.io/github/pdbpp/pdbpp/commit/6a07527dbf96d8d0534fc16ff90d77ad88ba9db3
```

**Comment by Flamefire** [comment] 2020-03-02 17:13
@drazisil The issue already exists and is caused by the values of “APPVEYOR” and “CI” env variables containing “True” but are tested for “true”. I suggest to make the test case insensitive.

see https://community.codecov.io/t/bash-script-does-not-detect-appveyor/1094

**Comment by drazisil** [comment] 2020-03-02 18:23
This appears to have broke due to https://github.com/codecov/codecov-bash/pull/138

Which was to correct https://github.com/codecov/codecov-bash/issues/125

Does Appveyor keep changing the case?

**Comment by drazisil** [comment] 2020-03-02 18:24
`APPVEYOR - True (true on Ubuntu image) if build runs in AppVeyor environment`

No, apparently they are inconstant. Ugg.

**Comment by Flamefire** [comment] 2020-03-03 07:40
There is even a PR waiting to be merged for 11 days: https://github.com/codecov/codecov-bash/pull/268

**Closed** 2020-03-03 13:51 UTC
Labels: bug, help wanted, needs deployment
